SUBSCRIPTION:
  RHN_USERNAME: <RHN_USERNAME>
  RHN_PASSWORD: <RHN_PASSWORD>
  FM_RHN_POOLID: <FM_RHN_POOLID>
  DOGFOOD_URL: <DOGFOOD_URL>
  DOGFOOD_ORG: <DOGFOOD_ORG>
  DOGFOOD_ACTIVATIONKEY: <DOGFOOD_ACTIVATIONKEY>
  CAPSULE_DOGFOOD_ACTIVATIONKEY: <CAPSULE_DOGFOOD_ACTIVATIONKEY>
URLS:
  HOTFIX_URL: <HOTFIX_URL>
SERVER:
  SERVER_HOSTNAME: <SERVER_HOSTNAME>